name = "SSAExecutionModule"
uuid = "c96e3573-cddc-40ac-bc73-ee1c3589917c"
authors = ["Magos-Biologis <127683931+Magos-Biologis@users.noreply.github.com>"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
ArgParse = "1.2.0"
PrecompileTools = "1.2.1"
